import type { Metadata } from "next";
import {Inter} from 'next/font/google'
import "./globals.css";

const fonte = Inter({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Seu evento começa aqui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={fonte.className}
      >
        {children}
      </body>
    </html>
  );
}
